config/routes.rb
Termbase::Application.routes.draw do
  
  resources :profiles
  resources :documents
  resources :locations

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup', to: 'users#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

  match '/signupgrp', to: 'groups#new'
  

  resources :password_resets
  resources :translations do
    resources :authorities
    member do
      post :copy
    end
  end  
  resources :groups
  resources :comments
  
  root :to => "translations#index"
  
  

  

end

app/models/translation.rb
class Translation < ActiveRecord::Base
  acts_as_versioned :table_name => :translation_versions
  
  serialize :metadata
    
  TRANSLATION_ILKS = ['Segment', 'Term']
  validates :ilk, :inclusion => TRANSLATION_ILKS
  
  validates_uniqueness_of :source_content, :scope => [:source_content, :target_content, :created_by_id, :group_id]

  

  
  attr_protected :version
  attr_accessible :document_id, :created_by_id, :type, :source_language_id, :source_content, :target_language_id, :target_content, :contexts_attributes, :metadata, :ilk, :created_at
  scope :rough_search, lambda {|query| where("source_content like ?", "%#{query}%").order(:updated_at) }
  scope :exact_search, lambda {|query| where("source_content = ?", "#{query}").order(:updated_at) }

  has_many :comments, :as => :commentable
  has_many :ratings, :as => :ratable
  
  has_one :created_by, :class_name => "User"
  
  belongs_to :group
  
  has_many :associations, :foreign_key => "associator_id"
  has_many :associateds, :through => :associations, :source => :associated
  
  
  
  has_many :contexts
  has_many :domains, :through => :contexts
  
  
  accepts_nested_attributes_for :contexts
  
  #allows for quick entry of terms by copying languages, type (seg, term), authority id
  def copy
    self.class.new.tap do |new_trans|
      attributes.each do |key,value|
        new_trans.send("#{key}=", value) unless key == "id"
      end
        new_trans.save
    end
  end
  
  
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: translation_versions
#
# * id                 :integer         not null
#   translation_id     :integer
#   version            :integer
#   source_language_id :integer
#   source_content     :string(255)
#   target_language_id :integer
#   target_content     :string(255)
#   created_by_id      :integer
#   group_id           :integer
#   metadata           :text
#   ilk                :string(255)     default Term
#   created_at         :datetime
#   updated_at         :datetime
#   versioned_type     :string(255)
#
#  Indexes:
#   index_translation_versions_on_translation_id  translation_id
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  
  before_filter :authorize, only: [:edit, :update]
  def index
    @translations = Translation.all
  end

  def show
    @translation = Translation.find(params[:id])
    @contexts = @translation.contexts.all
  end

  def new
    @translation = Translation.new
    @domains = Domain.find(:all, :order => 'code ASC')
    @tar_languages = Language.find(:all, :order => 'iso_code DESC' )

    #1 domain initially
    context = @translation.contexts.build
    
  end

  def create
    @translation = Translation.new(params[:translation])
    if @translation.save
      redirect_to @translation, :notice => "Successfully created translation."
    else
      render :action => 'new'
    end
  end

  def edit
    @translation = Translation.find(params[:id])
    @tar_languages = Language.find(:all, :order => 'iso_code DESC' )
    @domains = Domain.find(:all, :order => 'code ASC')
  end

  def update
    @translation = Translation.find(params[:id])
    if @translation.update_attributes(params[:translation])
      redirect_to @translation, :notice  => "Successfully updated translation."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @translation = Translation.find(params[:id])
    @translation.destroy
    redirect_to translations_url, :notice => "Successfully destroyed translation."
  end
  
  
  def copy
    original_translation = Translation.find(params[:id])
    @translation = original_translation.copy
    redirect_to edit_translation_path(@translation), :notice => "This is a copy of #{original_translation.source_content}"
  end
  
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<%= form_for @translation do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :source_language_id %><br />
	<%= f.collection_select(:source_language_id, Language.all, :id, :name) %>
  </p>
  <p>
    <%= f.label :source_content %><br />
    <%= f.text_field :source_content %>
  </p>
  <p>
    <%= f.label :target_language_id %><br />
	<%= f.collection_select(:target_language_id, @tar_languages, :id, :name) %>
  </p>
  <p>
    <%= f.label :target_content %><br />
    <%= f.text_field :target_content %>
  </p>
  <p>
    <%= f.label :type %><br />
    <%= f.text_field :type %>
	<% for context in @translation.contexts %>
		<%= f.fields_for :contexts do |context_form| %>
			<%= context_form.label :domain_id %><br />
			<%= context_form.collection_select(:domain_id, @domains, :id, :code, :prompt => true) %><br />
			<%= context_form.hidden_field(:translation_id) %>
		<% end %>
	<% end %>
  </p>
  <p>
    <%= f.label :metadata %><br />
    <%= f.text_area :metadata %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/translations/edit.html.erb
<% title "Edit Translation" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @translation %> |
  <%= link_to "View All", translations_path %>
</p>

app/views/translations/index.html.erb
<% title "Translations" %>

<table>
  <tr>
    <th>Source Language</th>
    <th>Source Content</th>
    <th>Target Language</th>
    <th>Target Content</th>
    <th>Version</th>
    <th>Type</th>
    <th>Metadata</th>
  </tr>
  <% for translation in @translations %>
	<span style="color:<%= cycle("red", "green", "blue", :name => "colors") -%>">
    <tr>
      <td><%= translation.source_language_id %></td>
      <td><%= translation.source_content %></td>
      <td><%= translation.target_language_id %></td>
      <td><%= translation.target_content %></td>
      <td><%= translation.version %></td>
      <td><%= translation.type %></td>
      <td><%= translation.metadata %></td>
      <td><%= link_to "Show", translation %></td>
      <td><%= link_to "Edit", edit_translation_path(translation) %></td>
      <td><%= link_to "Destroy", translation, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
	</span>
  <% end %>
<% reset_cycle("colors") %>
</table>

<p><%= link_to "New Translation", new_translation_path %></p>

app/views/translations/new.html.erb
<% title "Upload New Translation or Add to Local Database" %>

<%= render 'form' %>

<p><%= link_to "Back to List", translations_path %></p>

app/views/translations/show.html.erb
<div id="displaydata">
Term owned by: user/group<br/>	
	
<% @translation.attributes.each do |attr| %>
   <%= attr %><br />
<% end %>	
<br/>

</div>
Domain(s):
<% @contexts.each do |context| %>
	<%= Domain.find_by_id(context.domain_id).name %>
<% end %>	
<br/>

 

<div class="linksout">
<%= button_to 'Copy', copy_translation_path(@translation) %>
<p>
  <%= link_to "Edit", edit_translation_path(@translation) %> |
  <%= link_to "Destroy", @translation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", translations_path %>
</p>
</div>