config/routes.rb
Termbase::Application.routes.draw do
  
  resources :profiles
  resources :documents
  resources :locations

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup', to: 'users#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

  match '/signupgrp', to: 'groups#new'
  

  resources :password_resets
  resources :translations do
    resources :authorities
    member do
      post :copy
    end
  end  
  resources :groups
  resources :comments
  
  root :to => "translations#index"
  
  

  

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :type, :name, :access_code, :owner_profile_id, :owner_id



  has_many :memberships
  has_many :users, :through => :memberships
  
  has_one :owner, :class_name => 'User'
  has_one :owner_profile, :class_name => 'Profile'
  
  has_many :translations
  
  has_many :authorities, :as => :authoritable
  
  accepts_nested_attributes_for :translations
  
  before_save :generate_access_code
    
  private
  
     def generate_access_code
       #also handles duplicates, self because refers to group not instance var
       begin
         self.access_code = SecureRandom.urlsafe_base64(5)
       end while self.class.exists?(access_code: access_code)
    end
        
  
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: groups
#
# * id               :integer         not null
#   group_type       :string(255)
#   created_at       :datetime        not null
#   updated_at       :datetime        not null
#   name             :string(255)
#   access_code      :string(255)
#   owner_id         :integer
#   owner_profile_id :integer
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @access_code= @group.access_code
  end

  def new
    @group = Group.new
    @owner_profiles = Profile.find_all_by_user_id(current_user)
  end

  def create
    #use user-like login with user name + secure_code
    @group = Group.new(params[:group])
    if @group.save
      redirect_to @group, :notice => "Successfully created group."
    else
      render :action => 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to @group, :notice  => "Successfully updated group."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_url, :notice => "Successfully destroyed group."
  end
  

  
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name_for_group %><br />
    <%= f.text_field :name %>
  </p>
	<p>
		<%= f.label :choose_a_profile %><br />
		<%= f.collection_select(:owner_profile_id, @owner_profiles, :id, :real_name) %>
	</p>
		<%= f.hidden_field :owner_id, :value => current_user.id  %>
	
  <p><%= f.submit %></p>
<% end %>

app/views/groups/edit.html.erb
<% title "Edit Group" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @group %> |
  <%= link_to "View All", groups_path %>
</p>

app/views/groups/index.html.erb
<% title "Groups" %>

<table>
  <tr>
    <th>Group Type</th>
    <th>Name</th>
  </tr>
  <% for group in @groups %>
    <tr>
      <td><%= group.group_type %></td>
      <td><%= group.name %></td>
      <td><%= link_to "Show", group %></td>
      <td><%= link_to "Edit", edit_group_path(group) %></td>
      <td><%= link_to "Destroy", group, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Group", new_group_path %></p>

app/views/groups/new.html.erb
<% title "New Group" %>

<%= render 'form' %>

<p><%= link_to "Back to List", groups_path %></p>

app/views/groups/show.html.erb
<% title "Group" %>

<p>
  <strong>Group Code:</strong>
  <%= @access_code %>
</p>
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>


<%= @group.memberships.count %> members

 <%= link_to "Invite new member", '#' %>

<% if @group.memberships.present? %>
<p>
	Members:
	<%= @group.memberships.each do |member| %>
  		<%= member.name %>
</p>	
	<% end %>	
<% end %>
<p>
  <%= link_to "Edit", edit_group_path(@group) %> |
  <%= link_to "Destroy", @group, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", groups_path %>
</p>