config/routes.rb
Termbase::Application.routes.draw do
  
  resources :profiles
  resources :documents
  resources :locations

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup', to: 'users#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

  match '/signupgrp', to: 'groups#new'
  

  resources :password_resets
  resources :translations do
    resources :authorities
    member do
      post :copy
    end
  end  
  resources :groups
  resources :comments
  
  root :to => "translations#index"
  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates     :email, :presence => true,
                :format => { :with => email_regex },
                :length => { :maximum => 50 },
                :uniqueness => {:case_sensitive => false }
  #this also creates a virtual attr automatically called password_confirmation!!
  validates :password, :presence => true, :length => { minimum: 6 }, :on => :create
  validates :password_confirmation, :presence => true, :on => :create
  # validates_presence_of :password, :on => :create
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token



  # before_create { generate_token(:auth_token) }
  
  def send_password_reset
        generate_token(:password_reset_token)
        self.password_reset_sent_at = Time.zone.now
        save!(:validate => false)
        UserMailer.password_reset(self).deliver
      end
    

    def generate_token(column)
        begin
          self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
      end

  
      private
          #for users
          def create_remember_token
            self.remember_token = SecureRandom.urlsafe_base64
          end
  
  #predefined queries
  scope :by_name, order(:name)
  scope :subscribed, where(:subscribed => true) 
  
  has_many :translations, :as  => 'Owner'
  
  has_many :memberships
  has_many :groups, :through => :memberships
  
  has_many :former_groups, :through => :memberships, :source => :group, :conditions => [:expired => true]
  
  
  has_many :authorities, :as => :authoritable
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: users
#
# * id                     :integer         not null
#   name                   :string(255)
#   subscribed             :boolean
#   created_at             :datetime        not null
#   updated_at             :datetime        not null
#   email                  :string(255)
#   password_digest        :string(255)
#   remember_token         :string(255)
#   password_reset_token   :string(255)
#   password_reset_sent_at :datetime
#   location_id            :integer
#
#  Indexes:
#   index_users_on_remember_token  remember_token
#   index_users_on_email           email  unique
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @allusers = User.order("created_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @title = @user.name
    @profiles = Profile.find_all_by_user_id(@user)
    @allusers = User.order("created_at DESC")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @title = t(:signup)
    @user = User.new
   

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    #signs up the user once doing so login
    @user = User.new(params[:user])
    @allusers = User.order("created_at DESC")
    respond_to do |format|
      if @user.save
        log_in @user
        flash[:success] = t(:welcome_to_termbase)
        redirect_to locations_path 
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
    
  # Returns the Gravatar (http://gravatar.com/) for the given user.
    def gravatar_for(user, options = { :size => 50 })
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar", gravatar: options)
    end
  
  
end

app/views/users/_form.html.erb
<div class="row">
  <div class="span6 offset3">
		<% if @user.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@user.errors.count, "error") %> <%= t(:prevented_this_user_from_being_saved) %>:</h2>
		      <ul>
		      <% @user.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
	
		<%= form_for(@user) do |f| %>
		  

		  <div class="field">
		    <%= f.label :name %><br />
		    <%= f.text_field :name %>
		  </div>
		  <div class="field">
		    <%= f.label :email %><br />
		    <%= f.text_field :email %>
		  </div>
		  <div class="field">
			<%= f.label :password %><br />
			<%= f.password_field :password %>
		  </div>	
		  <div class="field">
			<%= f.label :password_confirmation, t(:confirmation) %><br />
			<%= f.password_field :password_confirmation %>
		  </div>
		  <%= f.submit t(:createmyaccount), class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Subscribed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.subscribed %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
<%= link_to t(:newgroup), new_group_path %>

app/views/users/new.html.erb
<h1><%= @title %></h1>

<%= render 'form' %>

<div>

app/views/users/show.html.erb
<h1>
<%= @user.name %>
</h1>
<p>
  	<%= gravatar_for @user %><br/>
	<%= @user.email %></br/>
</p>
<div class="profile_info">
<% if @profiles.present? %>	
		<% @profiles.each do |profile| %>
		<%= render :partial => "/shared/shared_show_profile", :locals => {:profile => profile} %>
		<% end %>
<% end %>
</div>

 <h1>Live Feed</h1>
    <p>	Live Feed Information Here.
							
			Other Users in the System:
			<br/>	
		<% @allusers.each do | user | %>	
			<%= user.name %></br/>
			<%= t(:membersince) %> 
			<%= time_ago_in_words(user.created_at) %><br/> 
		<% end %>
	</p>

<br/>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<%= link_to t(:createnewgrouporlogin), signupgrp_path %>